export const SET_QUERY_UPDATE_URL = 'SET_QUERY_UPDATE_URL';
export const SET_ISLOADING_STAUS = 'SET_ISLOADING_STAUS' ;
export const SET_ERROR_STATUS = 'SET_ERROR_STATUS';
export const UPDATE_MOVIES_ARRAY = 'UPDATE_MOVIES_ARRAY';
export const UPDATE_SINGLE_MOVIES_ARRAY = 'UPDATE_SINGLE_MOVIES_ARRAY';